### PR TITLE
Added autocomplete search suggestions along with test cases

### PR DESCRIPTION
**Pull request by SurajKamble**
Addressed issue #107.

### CODE REVIEW

**Comment by sebastian-code** [comment]
Hi @SurajKamble You refer in your code comments about a bug into the search view with articles. Do you mind to elaborate on that?

**Comment by SurajKamble** [comment]
@sebastian-code The search results do not show any articles related to the search query, could be because of the status=published condition. I might be wrong, please verify it once.

Also, is the autocomplete feature look fine to you? If so, please accept my PR.

**Comment by SurajKamble** [comment]
@sebastian-code I just checked it, the articles are only shown on the real website, but not on my local machine. I don't think that is a bug, please delete that comment. Thanks!

**Comment by sebastian-code** [comment]
Ah, ok, I saw already that behavior, but I disagree, it should show the results at both stages. I'll look into it; now I'm already applying some changes to your PR to improve readability and to implement additional checks.

**Comment by SurajKamble** [comment]
Sure thanks!!

**Comment by sebastian-code** [comment]
Checking it a little bit more, I think you found a real bug, the search view is not throwing data on the search term for Articles models.

**Comment by SurajKamble** [comment]
Yes, it doesn't. I will try looking into it too.

**Comment by sebastian-code** [comment]
Found it, solving in your branch because I don't want to start replicating this around too many times.

**Comment by SurajKamble** [comment]
Sure.

**Comment by sebastian-code** [comment]
Merged, added some changes and fixes. Many thanks @SurajKamble

**Comment by SurajKamble** [comment]
You're welcome.

**Pull request merged**
