### PR TITLE
Improved general UI & logic and added some features present in old version

### PR DESCRIPTION
**Pull request by gusbakker**
- Added password change page.
- #167 Restored the old crop profile image section and fixed profile images aspect ratio.
- Changed Notifications and News UI to a better looking.
- Added Bell notification with number count.
- Changed delete news posts to be removed by Ajax request.
- Updated migrations so ImageField is not anymore in User model (since upload mage has changed)
- #222 Added links in Notifications and fixed 'replied to' messages (still have to put the right addres to the links)
- Added unread Messages feature and improved its UI
- Added some unit tests

### CODE REVIEW

**Comment by sebastian-code** [comment]
@gusbakker can you fix the conflicts with the current status on the branch please?

**Comment by gusbakker** [comment]
@sebastian-code solved

**Comment by sebastian-code** [comment]
@gusbakker I ran the tests and PytTests throws the following errors:
```python
FAILED bootcamp/articles/tests/test_views.py::ArticlesViewsTest::test_draft_article - django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 110: 'endif', expected 'endblock'. Did you forget to register or load this tag?
FAILED bootcamp/articles/tests/test_views.py::ArticlesViewsTest::test_draft_article_change - django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 110: 'endif', expected 'endblock'. Did you forget to register or load this tag?
FAILED bootcamp/articles/tests/test_views.py::ArticlesViewsTest::test_index_articles - django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 110: 'endif', expected 'endblock'. Did you forget to register or load this tag?
FAILED bootcamp/news/tests/test_views.py::NewsViewsTest::test_delete_news - django.urls.exceptions.NoReverseMatch: Reverse for 'remove_news' with keyword arguments '{'pk': UUID('ea468a4b-5f26-4a68-b67d-330fe819dbdd')}' not found. 1 pattern(s) tried: ['news/remove/$']
FAILED bootcamp/notifications/tests/test_models.py::NotificationsModelsTest::test_delete_single_notification - AssertionError: assert 0 == 1
FAILED bootcamp/notifications/tests/test_models.py::NotificationsModelsTest::test_return_values - AssertionError: assert '<a href="/ot... content.</a>' == 'other_test_u...a0minutes ago'
```
PyLint checker throws the following error too:
```python
************* Module bootcamp.users.views
bootcamp/users/views.py:65:11: W0703: Catching too general exception Exception (broad-except)
bootcamp/users/views.py:97:11: W0703: Catching too general exception Exception (broad-except)
bootcamp/users/views.py:90:25: W1619: division w/o __future__ statement (old-division)
bootcamp/users/views.py:126:11: W0703: Catching too general exception Exception (broad-except)
************* Module bootcamp.users.models
bootcamp/users/models.py:66:15: W0703: Catching too general exception Exception (broad-except)
bootcamp/users/models.py:10:0: W0611: Unused user_logged_in imported from django.contrib.auth.signals (unused-import)
bootcamp/users/models.py:10:0: W0611: Unused user_logged_out imported from django.contrib.auth.signals (unused-import)
************* Module bootcamp.news.views
bootcamp/news/views.py:78:11: W0703: Catching too general exception Exception (broad-except)
bootcamp/news/views.py:14:0: W0611: Unused csrf imported from django.template.context_processors (unused-import)
************* Module bootcamp.notifications.views
bootcamp/notifications/views.py:82:11: W0703: Catching too general exception Exception (broad-except)
bootcamp/notifications/views.py:8:0: W0611: Unused HttpResponseForbidden imported from django.http (unused-import)
```
Some of the errors I'm seeing i think are related to your `master` branch being behind the current project status, perhaps syncing your branch with the most recent changes can help a little bit.

Can you check, please?

Also, don't forget to run Black after you finish editing your code, so it keeps the project styles.

**Comment by gusbakker** [comment]
@sebastian-code i want to merge changes from my develop branch. I don't want to push them to master, is it possible?
Btw, I'm looking at the pytest errors now

Articles error is already fixed now

**Comment by gusbakker** [comment]
The failed tests are now Fixed.
 _(The delete news test is temporarily commented i have to find a solution to ajax deletion)_

It seems all 96 tests are passing now.

I ran Black and files are successfully reformated.

**Comment by sebastian-code** [comment]
@gusbakker There is a ton of work in this PR, and I'll take some time to finish reviewing it. I guess I'll have a lot of questions about it, but I have to find them first. For now, I do have the following questions:
- In the notifications model, you modified the `__str__` method return structure, it looks a lot like the old method, is there a reason for that?
- You implemented a duplicated structure for notification handlers with some fixed features against the dynamic nature of the priors, what is the reasoning behind the new implementation?
- I see modifications to permissions on a lot of files:
  - Did you do that on purpose?
  - What is the purpose of those modifications?
  - Will those modifications affect existing instances running on the previous permission structure?
- I see you added a migration to the sites app but I don't see any real change, did I miss something?

**Comment by gusbakker** [comment]
@sebastian-code 
Yeah, there is a ton of work and we can revert some things if you don't agree. 
1.  I modified the __str__ structure as the old method allow to include links on it. Notifications should contain links to Actor and Verb. Maybe is there a better way to do it.
2. I implemented a new method to eliminate notifications. This allows notifications to be deleted if , for example, a user puts a Like on a news and removes that Like. The notification will be deleted in this case.
3. Where did you see those modifications to permissions? I don't know if there is some behavior of my PyCharm IDE.
4. I cant' see what are the changes you are talking about. Those 3 migrations in site app weren't there already?

But in general, is it going everything ok with the new features I added? Can you see if the changes are working fine in News, Notifications, Articles and Messages?

**Comment by sebastian-code** [comment]
@gusbakker did you check the coverage report, in your feature branch, it falls 6% againts development branch. Do you need help with that?

**Comment by gusbakker** [comment]
@sebastian-code hi, did you mean my develop branch in comparison to vitorfs develop branch? I will check that

**Comment by gusbakker** [comment]
I just added a new test that was commented. The delete_news test was now added to increase test coverage

**Pull request merged**
