### PR TITLE
Question upvote and downvote feature

### PR DESCRIPTION
**Pull request by arpit1997**
Added question upvote and downvote feature. Addressed issues #69

### CODE REVIEW

**Comment by sebastian-code** [comment]
Thanks @arpit1997 don't forget to add the tests for this new code

**Comment by arpit1997** [comment]
I will add the tests @sebastian-code

**Comment by arpit1997** [comment]
We have options as `selenium` and Django's default `TestCase` classes. So which one would you prefer?
@sebastian-code

**Comment by sebastian-code** [comment]
At least the `TestCase` test @arpit1997. Until now I haven't added selenium tests

**Comment by arpit1997** [comment]
Okay understood. Review this commit. I will work on the `TestCase`

**Comment by arpit1997** [comment]
@sebastian-code  added basic tests for question upvote and downvote. Please review the commits and let me know if there is any errors or changes you would like to have. PS: PR is pointing to develop branch.

**Comment by sebastian-code** [comment]
Hi @arpit1997 is there a reason to comment the favorites count segment inside the `partial_question.html` template?

**Comment by arpit1997** [comment]
Just the debug purpose no specific purpose

**Comment by sebastian-code** [comment]
Ok, and about the `print()` statements around the code? for the same purpose I assume?

**Comment by sebastian-code** [comment]
Up to now the code looks great @arpit1997, thanks a lot. My observations should be:

Uncomment favorites count segment.
Delete the print function call inside the `get_favoriters()` method.
The new code can use additional tests to validate the new methods.

And additionally, I'm not sure but I think than it would be nice to add the new votes count inside the question information block, perhaps below the favs and answers, or in between. What do you think about this last one? Perhaps this would clutter to much the space.

**Comment by sebastian-code** [comment]
Hey @arpit1997 don't worry. I did it already. I did it by hand to solve some things and also to add my own comments (still the need for more tests, but will come later). Thanks for your PR.

Merged.

**Comment by arpit1997** [comment]
@sebastian-code Please open an issue regarding more tests and assign it to me. I would love to complete that.

**Comment by sebastian-code** [comment]
Hi @arpit1997 I didn't saw your previous comment, sorry about it, I already solved that part on 2dee6da but thanks for the offering, if you want, you always can provide some PR with some tests.

**Comment by arpit1997** [comment]
@sebastian-code  I see that questions app does contain only one test for upvote and downvote feature. So I will try to add tests to questions app.

**Comment by sebastian-code** [comment]
Great @arpit1997 always a couple tests are welcomed. Fell free to push whenever you want to.

**Pull request merged**
