### PR TITLE
show summary in articles list page and fix the long word problem

### PR DESCRIPTION
**Pull request by WUJISHANXIA**
please review @sebastian-code!!

### CODE REVIEW

**Comment by sebastian-code** [comment]
Hi @WUJISHANXIA, thanks for the PR. I hope I can merge it; right now is not working due to the HTMLParser library. I assume than you're working with Python 2, but Bootcamp runs on Python 3 and has Python 2 backwards compatibility.

Please check the implementation so it will work with Python 3.

**Comment by WUJISHANXIA** [comment]
Hi @sebastian-code , I fix the bug for importing HTMLParser in python3. please review.

**Comment by sebastian-code** [comment]
@WUJISHANXIA I have been testing it and I'm still unable to make it work, I haven't been able to pin point the specific line, but I validated than the `SummaryParser` class is transforming the _markdown_ part in plan text. Can you check?

**Comment by WUJISHANXIA** [comment]
HI @sebastian-code , I have been testing it in python3 & python2, the result are shown below, and there is no error in my test. can you tell me what error happened in you test , or what do you mean about "I'm still unable to make it work" ?    so i can check for that :)

run app:

articles:

article:

**Comment by sebastian-code** [comment]
It stoped showing the images. Now it only renders plain text

**Comment by WUJISHANXIA** [comment]
@sebastian-code ，this is the change for the showing of articles list page, it only show 255 word for a article in the articles list page.  i think there is no need to show markdown content（like images）in the articles list page, it only need show summary plain text (255 word) in the articles list page. what do you think about this change?

1.only show  summary plain text (255 word) in the articles list page. 

2.show all markdown content in the article page

**Comment by sebastian-code** [comment]
The _articles_ app shows an image if the image was included at the beginning of the summary text, but with this change, the summary will show nothing, and when I open the article page, I can't see the image, it only show the markdown text as plain text.

Currently I'm using Python 3.5, Django 1.11.5, Mardown 2.6.9

**Comment by WUJISHANXIA** [comment]
"The articles app shows an image if the image was included at the beginning of the summary text, but with this change, the summary will show nothing"-----i think this is ok, it not need show image in the articles list page
"and when I open the article page, I can't see the image, it only show the markdown text as plain text."------i check it , this is a bug :(  .     
```
def get_content_as_markdown(self):
        self.content = self.insert_space_to_long_word(self.content) ----this may be damage the img url  when insert a space to a img url
        return markdown.markdown(self.content, safe_mode='escape')
```

**Comment by sebastian-code** [comment]
Yes, you're right. Commenting that line solved part of it. But I still think than showing the image is a good thing, but perhaps I'll change things a little bit, because I actually want to add a _highlighted image_ feature.

**Comment by WUJISHANXIA** [comment]
ok.

i find the function `get_summary_as_markdown` in the articles app ,but  there is no use of it.  is it for showing summary in the articles list page ?
```
    def get_summary(self):
        if len(self.content) > 255:
            return '{0}...'.format(self.content[:255])
        else:
            return self.content

    def get_summary_as_markdown(self):
        markdown_html = markdown.markdown(self.get_summary(), safe_mode='escape')
```

**Comment by sebastian-code** [comment]
Yes, that's basically the main purpose of that method.

**Comment by WUJISHANXIA** [comment]
I changed the partial_article.html, so it can be use to show  summary in the articles list page
```
  <div class="content">
      {% if is_articles %}
            {{ article.get_summary_as_markdown|safe }}
      {% else %}
            {{ article.get_content_as_markdown|safe }}
      {% endif %}
  </div>
```

**Comment by sebastian-code** [comment]
Merged

**Pull request merged**
