### PR TITLE
Python3 migration

### PR DESCRIPTION
**Pull request by sebastian-code**
I'm sorry but there is no another branch were to point this changes, I have tested almost all the functionalities and the code is working properly, but there is still room for further improvement.

The scope of this branch is to contain all the changes I make while I migrate the code base to Python3.

With this, my intent is to attend issue #49 but this is just as a consideration.

### CODE REVIEW

**Comment by qulc** [comment]
me too,  migrate to python3, 

https://github.com/qulc/bootcamp

but, my repo change too many othercode

**Comment by dwayne** [comment]
@sebastian-code Are you still working on this PR? I'd be happy to contribute, what's holding this up? Do you need help?

**Comment by sebastian-code** [comment]
Hi @dwayne At this point this PR is functional up until I'm able to validate, and there is no problem I'm aware of; I would say than this is being in hold because is waiting to be approved and merged by @vitorfs.

I have to check the code to validate if there is some pending work into it, because I left the PR in it's actual state because I was waiting a response.

**Comment by vitorfs** [comment]
Sorry for holding it back guys!
I merged the pull request
Also added python 2 compatible decorator to the models, so to keep it working on both Python 2 and 3
I was thinking about improving the quality of the project (I developed it like 2 years ago or something)
Things on my list: isort, coverage, flake8, tox to run tests on both python 2 and 3, and start adding some unity tests

**Pull request merged**
